apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kevintest
  namespace: development
spec:
  metadata:
      namespace: development
  chart:
    spec:
      version: "1.0.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
