apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-development
resources:
  - namespace.yaml
  - ../base/platform-test-svc
patches:
  - path: platform-test-svc-values.yaml
    target:
      kind: HelmRelease
      name: platform-test-svc
