apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: platform-test-svc
  namespace: platform-development
spec:
  chart:
    spec:
      version: "1.0.0"
  test:
    enable: false
