apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: platform-test-svc
  namespace: platform-qa
spec:
  chart:
    spec:
      version: "1.0.0"
  test:
    enable: false
  values:
    image:
      tag: 1.1.0
